### ISSUE TITLE
Sensoren beschrijven

### ISSUE THREAD

**Issue by thomascrmbz** [vives-projectweek-2021/project-repository-turbineboosters#4]
Omdat de sensor hat gecombineerd zal worden met een andere opdracht zitten er al een paar sensoren standaard op.
De extra sensoren moeten nog beslist worden.

**Comment by thomascrmbz** [comment]
Standaard sensoren die er al op zitten
- BME sensor (luchtkwaliteit)
- lichtsensor
- 2 drukknoppen
- LCD display
- ADC
- RGB LED
- LED
- Motor driver (kleine motors zoals een ventilator)

**Comment by dylanmsu** [comment]
We kunnen er misschien een vibratie sensor op zetten om te weten wanneer de turbine te hard trilt. Moest dat niet kunnen we er een rotatiesnelheid-meter in implementeren en dan de belasting verhogen als het te snel draait.
