### ISSUE TITLE
Metingen motor doen

### ISSUE THREAD

**Issue by thomascrmbz** [vives-projectweek-2021/project-repository-turbineboosters#6]

**Comment by dylanmsu** [comment]
Na het meten van de motor kwam ik tot de conclusie dat deze ongeschikt is voor onze toepassing, omdat de inductie motor moeilijk te gebruiken is als generator. Als we dit dan toch wilden doen hadden we complexe schakelingen nodig en ging sowiso een slechte efficientie geven. Voor die reden opteren we een driefasige synchroonmotor te gebruiken die we kunnen aankopen of gebruiken van school.

**Comment by thomascrmbz** [comment]
Ik denk dat het handig is om een denkbeeldige motor te nemen en specificaties op te stellen, zodat we daarmee ons pcb board kunnen maken en dan later op zoek gaan naar de motor die aan onze vereisten voldoet.
